### ISSUE TITLE
Access to more than sink / source 0

### ISSUE THREAD

**Issue by atypicalleon** [bondagit/aes67-linux-daemon#15]
How can I access other sinks or sources other than ID 0, e.g. source with ID 1 with command-line utilities like aplayer, arecord or mpg123?
I tried mapping the "channels" of the hw:RAVENNA card in /etc/asound.conf. However, in the case of a source, all sources just output to the ip-address of sink 0 or they stay silent. In the web ui of AES67 Daemon, I configured the sources to use ALSA output 1>2, ALSA output 3>4,... (for 2 channel audio). Am I working in the right direction? 

This is my /etc/asound.conf:
```
pcm.network {
   type hw
   card 0
}

ctl.network {
   type hw
   card 0
}


pcm.dev01 {
   type plug
   slave {
      pcm "network"
      channels 2
   }
   ttable.0.0 1
   ttable.1.1 1
}

pcm.dev02 {
   type plug
   slave {
      pcm "network"
      channels 2
   }
   ttable.0.2 1
   ttable.1.3 1
}
```

**Comment by bondagit** [comment]
Hi there, at present it's not possible to use the ALSA plugins with the RAVENNA device.
The reason is that the diver supports memory mapped access mode but with indirect PCM transfer and the ALSA library doesn't support this transfer mode. See issue #7 for additional details.
So, retuning to your question you can use all the configured Sources and Sinks but you have to playout or record them simultaneously.
The good news is that I am currently re-working the driver to implement direct PCM transfer and I will be releasing these changes soon.

**Comment by atypicalleon** [comment]
Hi, thank you very much!
This explains why (while data is being sent out) only zero-samples can be received as soon as any ALSA plugins are in use for any number of sources.
Please keep up the good work, this is really a nice project offering a lot of things to learn from.
