### ISSUE TITLE
Allow configuring a sample rate of 88200 Hz?

### ISSUE THREAD

**Issue by m7a** [bondagit/aes67-linux-daemon#173]
Hello,

I am using the `aes67-linux-daemon` successfully in conjunction with an MERGING+ANUBIS interface. Currently, I am trying to debug some speaker issue and for this purpose wanted to configure 88.2kHz sample rate.

It seems that this sample rate is supported in all of the necessary places because when I add it in the JSON, it gets picked up upon daemon restart and works nicely. However, the GUI does not permit configuring this sample rate as it seems?

Is there a particular reason for this? Would it be feasible to add 88.2kHz as an additional choice? Is it as simple as adding another option here? <https://github.com/bondagit/aes67-linux-daemon/blob/3d240fd406d8636df8b6e24cf7c947b05e48a691/webui/src/Config.jsx#L221>

Thank you very much for this helpful program :smile:

**Comment by bondagit** [comment]
I confirm that sample rate 88200Hz is supported by the daemon and the driver. It's missing in the WebUi just because it's not common.
As you mentioned It can be easy added just adding a new config option in [aes67-linux-daemon/webui/src/Config.jsx](https://github.com/bondagit/aes67-linux-daemon/blob/3d240fd406d8636df8b6e24cf7c947b05e48a691/webui/src/Config.jsx#L221):
` <option value="88200">88.2 kHz</option> `

**Comment by m7a** [comment]
> It's missing in the WebUi just because it's not common.

Indeed, I don't think it is widely used, either. Here, it seems to allow me to work around some EMI issue with the monitors while at the same time still providing sufficient sample rate for me not to hear any differences compared to 96kHz which I was running before.

> I can release this change in the next daemon version.

This would be very much appreciated, thank you :smile:

**Comment by bondagit** [comment]
this, together with additional minor changes, is now part of release v2.0.1
