### ISSUE TITLE
Accessing additional ALSA outputs

### ISSUE THREAD

**Issue by Aika0** [bondagit/aes67-linux-daemon#28]
I'm sorry for asking this as well... I know it's not directly related to the daemon you've created (which I'm really appreciating) but to the full use of the sources it can create. I can access the first pair of ALSA outputs readily enough (I looked at the run_demo.sh) but I'm not sure how to access additional pairs of ALSA outputs (for example, ALSA Outputs 3 & 4 for a second source.

I tried using the asound.conf like this:
pcm.test4 {
  type plug
  slave.pcm {
    type dmix
	ipc_key 0x11113
	slave {
      pcm "hw:CARD=RAVENNA"
	  rate 48000
      format S24_3LE
	  channels 32
	}
	bindings {
	  0  2
	  1  3
	}
  }
}

I've also tried a few other configurations, but I can't seem to figure out how to actually send audio to the ALSA in a way that it's coming over my second source where the Audio Channels map is set to ALSA Output 3 -> ALSA Output 4.

Any help would be greatly appreciated!

Thank you

**Comment by bondagit** [comment]
So let's assume that you have created a pair of L24 48Khz stereo sources associated with the ALSA channels [0,1] and [2,3] respectively and you want to play them separately, you can do it using the DMIX plugin.

From  _~./asoundrc_
```
pcm.source_1 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
    }
    bindings { 0 0 1 1 }
}

pcm.source_2 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
    }
    bindings { 0 2 1 3 }
}
```

Once the PTP clock is locked you can playback on the two sources independently by using:
```
aplay -D plug:source_1 ./file1.wav  -vv 
aplay -D plug:source_2 ./file2.wav  -vv 
```

Please consider you can now do this because I have patched the Merging driver to operate in direct PCM transfer mode. With the original driver code this was not possible.

**Comment by Aika0** [comment]
Thank you so much. I have it working. For reference (in case anyone could use it) I'm attaching my asoundrc which I made to do 10 stereo aes67 (48/24 only) streams. I think it's working correctly.
[asoundrc.txt](https://github.com/bondagit/aes67-linux-daemon/files/5850780/asoundrc.txt)

**Comment by bondagit** [comment]
Cool ! It's good to hear that.
Keep in mind that the maximum number of sources you can handle at the same time depends on the performance of your system and in particular in its capability to serve all the active playbacks within a certain time.
If you experiment underrun errors, you may have reached your system limit.

**Comment by calanor** [comment]
How can I know if one stream is in underrun?
Is it possible that this wav sample  with distortion that I attached is due to underrun?

This happens after a few minutes of listening and sometimes it lasts a few seconds and other times I have to restart the listening so that the distortion disappears.

My aosund.rc it is similar to your example.  I configure 32 channels but I use only one mono at a time in this example.

[testaes64.zip](https://github.com/bondagit/aes67-linux-daemon/files/5857776/testaes64.zip)

**Comment by bondagit** [comment]
Hi Calanor, 
the description I provided of the underrun condition was related to the handling of multiple playbacks on the ALSA outputs.
In case an underrun occurs when using aplay the application produces the "Underrun!!!" message. aplay is able to resume from this situation but the receiver will miss some audio samples. The message you see (if any) depends on the specific player application you are using.
This event means that the player didn't feed the requested audio samples within a certain period and this can happen for multiple reasons including processes scheduling.
In your stream it looks like you are missing audio samples and this might be caused by multiple reasons: playback underrun, late  and or dropped packets, recording underrun/overrun, ....
My suggestion is to look into the player and the recorder logs/diagnostics and to analyze the RTP stream using Wireshark.
The analysis and resolution of this type of problems is however out of context with this particular issue and the daemon itself.
