### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Ashymad** [bondagit/aes67-linux-daemon#3]
Great project. However I don't understand how can I play and receive a stream over the network. Currently what I'am trying:
A PC with ptp master running + 2 RPis with aes67-deamon.
I can connect to the WebUIs and add sinks for the second device. I can see that PTP is working and both RPis are locked to the master. However after i alsarecord on one RPi and speaker-test on the second one (like in the demo) all I get is silence if I try to play the recorded file back. Could you help me understand how to configure this?

I can add a small writeup to the README on confguration after, so that the next person has an easier job.

**Comment by bondagit** [comment]
Yes, I didn't include any specific usage guide. 
The demo can be used as a starting point to build custom configurations.
The idea here is that a source is used to send RTP audio packets and a sink is used to receive RTP audio packets from a specific source. The driver creates the paths between the ALSA devices and the network streams. 

Returning to the configuration:
First of all make sure you are using the Ethernet network device in your daemon configuration on both the RPIs.
Then in your setup by using the WebUI you can configure a source on RPI and a sink on the other. 
When creating the sink you can either copy the source SDP file manually or specify the HTTP address of the of the source SDP (something like _http://[source_ipaddr]:8080/api/source/sdp/1_ , assuming this is source with id 1).
When source and sink are configured, and you have a PTP master on the network, you just need to wait for the PTP slaves to sync.
After that you can start playback on the source with:
> speaker-test -D plughw:RAVENNA -r 44100 -c 2 -t sine 
and record on the sink with:
>arecord -D plughw:RAVENNA -c 2 -f cd -d 30 -r 44100 -t wav sink.wav
assuming you have configured stereo audio @ 44,1Khz.
You can monitor the status of the sink by using the WebUI and clicking on the Sinks tab. When the sink receives packets you should see "receiving" in the status field.
Valuable tools in case of troubles are Wireshark and tcpdump: you can try capturing and analysing the RTP traffic (UDP port 5004 by default)  on the source, on the PC, and on the sink.

**Comment by Ashymad** [comment]
I've identified a few problems (thanks for suggesting Wireshark):
1. RTP Packets are sent out to MAC address of the sender and subsequently bounced on a nearest network switch
https://github.com/bondagit/aes67-linux-daemon/blob/f57046a4783193e6ea041ec1b09f4cee57c06d52/daemon/session_manager.cpp#L475-L476
Here you set the destination MAC to a sender's interface MAC, while it should be a multicast MAC corresponding to RTP multicast IP address.
I've hardcoded a multicast mac address in the code to check it and indeed it works this way

2. The RTP packets are only received on the clients if wireshark is recording, stopping wireshark stops transmission, and starting again starts it again. Maybe you need to join the multicast group in the daemon or sth?
3. `std::list` seems to be defined in `<list>` header on newer systems, it needs to be included to compile the daemon

After dealing with these the setup is working very well, however I've 2 additional questions/nitpicks:

4. Is there a way to tell the driver to synchronize to a local clock (or a a hw nic ptp clock /dev/ptpX) instead of PTP? This would allow to have the PTP master and the master source on the same machine.
5. Although the devices have synced clocks the audio streams seem to be synchronized very poorly (I've checked it on an oscilloscope). Do you know if there is any resampling done in the driver? How is sample synchronization performed if at all?

Finally, thanks for your explanation :)

**Comment by bondagit** [comment]
Hi, thanks a lot for your feedback and the tests.  Please find my comments below:

1. Yes, this has been fixed by dff3ab3 .  At present It’s not clear to me why I couldn’t spot this problem during my tests. Anyway thanks again !
2. I cannot reproduce this problem. The daemon already handle  IGMP membership for both the source and sink RTP multicast addresses. You can verify your multicast membership with the command: 
 _> netstat –g_ 
You should have an entry for each configured stream like the following:
_> eth1            1      239.1.0.1_
It can be that the problem is related to point 1. Can you please retry after applying the fix?
3. This was not an issue with the compilers I tested so far but I added inclusion of <list> header in dff3ab3
4. To my knowledge no, but his would be cool. Please note that ptp4l explicitly disables (with IP_MULTICAST_LOOP option) the reception of self-generated messages, otherwise it would be possible to receive local PTP announcements (not the most elegant way to sync on the local clock anyway… )
5. First of all consider that the driver has been developed by Merging Technologies and the daemon works under the assumption that this is running smoothly … 
Having clarified this, I have created a few patches to compile it with kernel 5.x and to make it work for ARMv7 platform and I can answer some of your questions: 
    > Do you know if there is any resampling done in the driver?

    To my knowledge the driver is not doing any sample rate conversion but depending on your configuration the ALSA subsystem instead might do it. To verify the ALSA audio chain and the capture/playback parameters use the option _–vv_ when using _arecord_ or _aplay_ tools
   > How is sample synchronization performed if at all?

    Yes, it’s performed by the driver (sources are cloned in the directory _3rdparty/ravenna-alsa-lkm/driver/)_ by the function:

    int **ProcessRTPAudioPacket**(…)  in file RTP_**audio_stream.c**,  around line 752

    The incoming RTP packet is inserted in the ALSA circular buffer of the capture device at an offset that is computed accounting for the packet RTP timestamp, the configured playout delay (offset from the reference clock as signaled by the SDP file) and the current PTP clock.  A high resolution timer with a base period of  1333333 ns  is used for PTP clock processing, see module_timer.c and PTP.c . 
Feel free to explore the sources of the driver if you need additional details ;-) . I didn’t test if the synchronization is working as expected.

Some additional notes:

PTP and RTP packets processing is fully implemented in the kernel module to minimize latencies and the RTP and PTP packets never reach the user space and are consumed and injected by the kernel module using Linux _netfilter_. The daemon communicates with the driver for control, configuration and status monitoring only by using _netlink_ sockets.

Assuming the driver is syncronizing the the streams as expected you should consider that Linux (in the standard configuration) is not a real time OS and latencies may impact the performance in various stages including ALSA playback & record.

To tune your Linux kernel you can refer to the Merging Technologies README at:
https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/
section Prerequisite.

In addition to this you could try compiling and configuring the Linux Kernel with the Real Time patch, see:
https://rt.wiki.kernel.org/index.php/Main_Page

**Comment by Ashymad** [comment]
Ad. 2: I've checked and now everything is working as expected, I've no idea why I had this problem with Wireshark.
Ad. 5: Now I see how this works. It is a virtual device that is clocked not by the system clock by by the media clock. I was trying to use alsaloop to play the audio from the stream but this did not work as expected because of the clock difference. I am however able to use Jack to make this work a bit better.
I don't have any more questions so I'll close this. Thanks for your time and detailed explanations :)

**Comment by bondagit** [comment]
Thanks a lot for your feedback !
I don't know much about Jack.  If want to contribute into the project you are very welcome .
An additional section about Usage in general and/or usage with Jack for example would be really cool ;-)
In my previous comment I forgot to mention that the driver also support memory-mapped (mmap) I/O mode for the audio streams (option -M with aplay/arecord) that could potentially further decrease the latency.
