### ISSUE TITLE
Is it needed to run ptp by yourself

### ISSUE THREAD

**Issue by GrauBlitz** [bondagit/aes67-linux-daemon#35]
Maybe i am missing something here, i started the daemon and configured one device as the source and the other as a sink. So long everything fine. But the PTP tabs stays by Mode=Slave, Status=Unlocked and GMID = 00-00-... Do i need to run the ptp4l on the sink or the source host?

**Comment by GrauBlitz** [comment]
Also the sink is listed with only mono channel when checking alsamixer, but i configured Channels=2 on the Sinks tab.

**Comment by GrauBlitz** [comment]
Also as i read the other issue with RPi support: I can assist with that, im currently running on Arch ARM with the newest Kernel on the RPi CM4 Platform. I also created a compile script for this platform so if everything is running/working as expected i can help with testing and additional script files :-)

**Comment by bondagit** [comment]
The driver works as PTP slave only. This means you need to have a PTP clock master on the network. Since by default ptp4l multicast traffic is not received on the network device where it's running (with the only exception of the lo device) if you don't have another clock master on the network you have to run ptp4l on a third device.
The device where ptp4l is running cannot see the PTP packets because ptp4l explicitly disables the multicast loopback option. This can be modified by patching and recompiling ptp4l.

**Comment by GrauBlitz** [comment]
So its not possible to run this config (1 slave, 1 source directly connected) by two devices? I will check out the option you mentioned. Thank you!

**Comment by bondagit** [comment]
Starting from daemon version v1.1 you can run a PTP master clock on the same daemon host.
You can use ptp4l but you have to patch it to enable multicast loopback. See #34 
Otherwise you need another device to run as master clock on you network.
