### ISSUE TITLE
No sound using dshare in asound.conf

### ISSUE THREAD

**Issue by keygee** [bondagit/aes67-linux-daemon#7]
Hi Andrea,
I'm trying to use aes67-linux-daemon to send multiple audio channels from different applications to a  sink.
this is my /etc/asound.conf:

```
pcm.1LR {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:0" # card onboard
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 0
		1 1
	}
}

pcm.1L {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:0" # card onboard
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 0
		1 0
	}
}

pcm.1R {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:0" # card onboard
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 1
		1 1
	}
}

pcm.2LR {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:2" # Merging ravenna
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 0
		1 1
	}
}

pcm.2L {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:2" # Merging ravenna
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 0
		1 0
	}
}

pcm.2R {
	type dshare
	ipc_key 1234
	ipc_key_add_uid 1
	slave {
		pcm "hw:2" # Merging ravenna
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 48000
		channels 2
	}
	bindings {
		0 1
		1 1
		
	}
}

```
With this, I can run

    aplay file1.wav -D1L &
    aplay file2.wav -D1R

and hear the 2 files on 2 separate channels with my on board card, but if I try

    aplay file1.wav -D2L &
    aplay file2.wav -D2R

I see no errors but no sound in the sink.
If I run

    aplay file1.wav -Dhw:2

I can hear the sound perfectly on the sink.

Can you suggest me other test?

Thank you a lot for this very nice and useful project

Cheers

Guido

**Comment by bondagit** [comment]
Hi Guido,
thanks for reporting this problems.
I can reproduce it but at present I don't know the root cause of it.
Andrea

**Comment by bondagit** [comment]
I did some tests and it looks like the problem is related to the fact that the dshare plugin is feeding the Ravenna driver with silence instead of the audio file samples. 
Indeed after playback on the dshare plugin I can see the following messages:
```
> dmesg | grep silence
...
[28369.540534] mr_alsa_audio_pcm_playback_silence called for 48 frames at pos 816
[28369.541142] mr_alsa_audio_pcm_playback_silence called for 48 frames at pos 864
[28369.542400] mr_alsa_audio_pcm_playback_silence called for 48 frames at pos 912
```
The dshare plugin (and also dmix) requires the driver to expose the mmap interface and it also uses such interface.
Attempt to use the driver mmap interface directly by using option (-M) in aplay is successful but when using the plugin I always have the problem explained above.

**Comment by bondagit** [comment]
I could solve this issue by applying a temporary fix to the [ALSA library](https://github.com/alsa-project/alsa-lib/).
See https://github.com/alsa-project/alsa-lib/issues/51
I wiil wait for their feedback to understand how to proceed.

**Comment by keygee** [comment]
Hi Andrea,
I can confirm your patch works great on CRUX distribution with kernel 5.6.10 and alsa-lib 1.2.2 with your patch.
Thank you very much
Guido

**Comment by bondagit** [comment]
Hi Guido,
according to alsa-project/alsa-lib#51 the dshare plugin doesn't support ALSA driver using indirect PCM transfer. The fix I applied to the alsa-lib can produce some results but cannot be considered a final solution because it might not work properly with concurrent clients.
The only clean solution would be to have a driver that uses the direct PCM transfer.
