### ISSUE TITLE
daemon restart needed after audio device restart

### ISSUE THREAD

**Issue by vilnic** [bondagit/aes67-linux-daemon#95]
Hi, trying to build a system that would be quite robust and could survive different outages. 
System that receives audio from Dante/aes67 and transcodes it for IP delivery. 
For now it "survives" network loss between audio source device and transcoder - the audio appears after network connection is restored without any restarts needed. 
BUT the problem is when the audio device reboots - then the audio will not recover unless the aes67-daemon and transcoding process is restarted. 
I have a suspicion that it could be related to that session version value changes in SAP/SDP message (judging from Wireshark trace), maybe also change in mediaclk (media clock offset) parameter value. And RAVENNA/AES67 driver inability to recognise it as a same session and continue to copy RTP packets to ALSA, although multicast is still received. 
In the setup the audio device is not a PTP source. 

Understood that you have made a few patches to this AES67 driver already - maybe some hints on where to update in this case? Maybe even make it as an improvement in your code?

**Comment by bondagit** [comment]
Hi there,
I suspect the problem is a change in the SSRC identifier of the RTP packets sent by the source after a restart.
The Synchronisation Source identifier uniquely identifies the source of a stream.
Basically when the driver starts receiving RTP packets for a new Sink it locks on the RTP SSRC and discard any other incoming RTP packets with a different SSRC.
See [RTP_audio_stream.c:583 ](https://github.com/bondagit/ravenna-alsa-lkm/blob/cdd64d2358b684e7d9d3eacc12f547b3f58abd5e/driver/RTP_audio_stream.c#L583)
Although you can disable the check there are good reason to keep it.

**Comment by bondagit** [comment]
You can use Wireshark to verify if this is the case.

**Comment by vilnic** [comment]
Thanks, @bondagit ! 
If failed exactly at this SSRC change check. 
Quick and dirty test to comment lines 583-599 managed to recover audio flow after audio device restart. 
Now will have to figure out how to do it more proper way. :)
