### ISSUE TITLE
No way to create a receiver

### ISSUE THREAD

**Issue by chabad360** [bondagit/aes67-linux-daemon#98]
There doesn't seem to be any way to create a routeable input only a sink with a defined input. It would be really helpful if there was some way to do that.

**Comment by bondagit** [comment]
What do you mean by routable input ? Can you please elaborate ?

**Comment by chabad360** [comment]
I mean an input(/receiver?) that shows up in routing managers.

**Comment by bondagit** [comment]
Use the Sinks tab on the WebUI to create a receiver.
You can specify a receiver manually by entering the associated SDP file or choose one of the available Sources detected on the network via SAP or mDNS (click on "Use SDP" checkbox to activate these).
Otherwise you can specify the URL to the SDP file of the Source.

**Comment by bondagit** [comment]
any update ?

**Comment by chabad360** [comment]
Been a bit busy with a show and I've been having trouble getting ptp working, which might be an issue too.
